'use strict';

// Messenger API parameters
const FB_PAGE_TOKEN = "EAADUwQRj73gBABs8E0EiVWgbcI1i8WF97Wkz3vNUZCULFpYrQ78xZA14CaFZCM4cHutPgqG2dqi40JKZC7fzAJ8CWXpiBO19aRnRFG3H9x8gj53FWsBIUfVs9grXFuly8NFzYCEfTgiMZBG00gZCh2B2GAZAFvr3ZCaPUczHeSIhdwZDZD";
var FB_VERIFY_TOKEN = process.env.FB_VERIFY_TOKEN;
if (!FB_VERIFY_TOKEN) {
    FB_VERIFY_TOKEN = "Health";
}

module.exports = {
    FB_PAGE_TOKEN: FB_PAGE_TOKEN,
    FB_VERIFY_TOKEN: FB_VERIFY_TOKEN,
};